name: FromScratch

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'src/**'

jobs:
  first-actions:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: CheckOut Code
        uses: actions/checkout@v4
      
      - name: Get git Reference
        run: "echo job: ${{github.job}}"   

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Main Script
        run: python src/script.py

      - name: Run ls
        run: |
          echo $(date)
          ls -la

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5     
        with:
          commit_message: Git AutoCommit 
          file_pattern: '*.txt'

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Depploy
        run: echo "Deploying branch ${{ github.ref }}"



  second-action:
    runs-on: ubuntu-latest
    needs: [first-actions, deploy]
    steps:
      - name: Show Output Second Action
        run: "echo job: ${{github.job}}"

  third-action:
    runs-on: ubuntu-latest
    needs:  [first-actions, deploy]
    steps:
      - name: Show Output Third Action
        run: "echo job: ${{github.job}}"

  convergence-action:
    runs-on: ubuntu-latest
    needs: [second-action,third-action]
    steps:
      - name: Show Output
        run: "echo job: ${{github.job}}"   

  docker-action:
    runs-on: ubuntu-latest
    needs: [second-action,third-action, convergence-action]
    steps:
      - name: Docker Step
        uses: docker://alpine:3.8  
      
  cancelled-action:
    runs-on: ubuntu-latest
    steps:
      - name: cancelled-action
        if: ${{cancelled()}}
        uses: "echo job Cancelled"      

         