name: From Hell

on:
  workflow_dispatch:

jobs:
  Another:
    runs-on: ubuntu-latest
    env:
      ENVIDIA: "ENVIDIA env vars"
      MY_NAME: "Mona The Octocat"
    permissions:
      contents: write
    steps:
      - name: "First Step"
        id: first
        run: |
          echo "ENTORNO=TEST" >> $GITHUB_OUTPUT
          echo "::debug::Set ENTORNO variable"

      - name: "Read ENV"
        run: |
          echo "ENV: ${{steps.first.outputs.ENTORNO}}"
          echo "ENVIDIA: $ENVIDIA"
          echo "::add-mask::$MY_NAME"

      - name: Set environment variable
        run: echo "MY_ENV_VAR=myValue" >> $GITHUB_ENV
  
      - name: Use environment variable
        run: |
          echo "The value of MY_ENV_VAR is $MY_ENV_VAR"
        
      - name: Set the value in JSON_RESPONSE
        id: step_curl
        shell: bash
        run: |
          {
            echo 'JSON_RESPONSE<<EOF'
            curl https://jsonplaceholder.typicode.com/todos/1 | jq 
            echo EOF
          } >> "$GITHUB_ENV"
          {
            echo 'JSON_RESPONSE_OTHER<<EOF'
            curl https://jsonplaceholder.typicode.com/todos/1 | jq 
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Use environment variable
        run: |
          echo "The value of JSON_RESPONSE is $JSON_RESPONSE"
          echo "The value of JSON_RESPONSE is ${{steps.step_curl.outputs.JSON_RESPONSE_OTHER}}"  